### ISSUE TITLE
Trying to run export-entries without first running export fails.

### ISSUE THREAD

**Issue by Tigatok** [contentstack/contentstack-export#43]
It appears that when I try to export-entries as the first command (and probably other export-* commands), the proper directories are not created, and the command fails.

```
info: Starting entry migration
ER TypeError: Cannot read properties of undefined (reading 'length')
    at /home/tmarshall/clients/red/migration/contentstack-export/lib/export/entries.js:51:25
    at Promise._execute (/home/tmarshall/clients/red/migration/contentstack-export/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/tmarshall/clients/red/migration/contentstack-export/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/tmarshall/clients/red/migration/contentstack-export/node_modules/bluebird/js/release/promise.js:79:10)
    at exportEntries.start (/home/tmarshall/clients/red/migration/contentstack-export/lib/export/entries.js:46:10)
    at /home/tmarshall/clients/red/migration/contentstack-export/app.js:35:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Failed to migrate entries
error: {}
Done in 0.21s.
```

It looks like the failure is coming from helper.js exports.readFile command.

The proper dirs are not created and it cannot find them.

**Comment by cs-raj** [comment]
Hi @Tigatok 
We are about to deprecate this utility and is not maintained by us
Can you please use the contentstack [cli export ](https://www.contentstack.com/docs/developers/cli/export-content-using-the-cli).

cc: @netrajpatel @aman19K
